### ISSUE TITLE
Issue with Snappyer

### ISSUE THREAD

**Issue by epinault** [kafka4beam/kafka_protocol#100]
Hello, 

I am using elixir 1.13 and OTP 24.1.7 (and latest version of brod)

I am tryting to use Brod with snappyer. But seems that the instructions is to follow kafka_protocol 

I tried this 

```
Application.put_env(:kafka_protocol, :provide_compression, [{:snappyer, Arth0.Publishers.Kafka}])
```

and then started my producer in brod with the config

```
compression: "snappyer"
```

but I am getting this error

```
[error] GenServer #PID<0.845.0> terminating
** (FunctionClauseError) no function clause matching in :kpro_compress.get_module/1
    (kafka_protocol 4.0.1) /Users/emmanuelpinault/podium/arth0/deps/kafka_protocol/src/kpro_compress.erl:93: :kpro_compress.get_module("snappyer")
    (kafka_protocol 4.0.1) /Users/emmanuelpinault/podium/arth0/deps/kafka_protocol/src/kpro_compress.erl:86: :kpro_compress.do_compress/2
    (kafka_protocol 4.0.1) /Users/emmanuelpinault/podium/arth0/deps/kafka_protocol/src/kpro_batch.erl:78: :kpro_batch.encode_tx/4
    (kafka_protocol 4.0.1) /Users/emmanuelpinault/podium/arth0/deps/kafka_protocol/src/kpro_req_lib.erl:250: :kpro_req_lib.produce/5
    (brod 3.16.1) /Users/emmanuelpinault/podium/arth0/deps/brod/src/brod_producer.erl:419: :brod_producer.do_send_fun/4
    (brod 3.16.1) /Users/emmanuelpinault/podium/arth0/deps/brod/src/brod_producer_buffer.erl:276: :brod_producer_buffer.do_send/4
    (brod 3.16.1) /Users/emmanuelpinault/podium/arth0/deps/brod/src/brod_producer.erl:525: :brod_producer.maybe_produce/1
    (brod 3.16.1) /Users/emmanuelpinault/podium/arth0/deps/brod/src/brod_producer.erl:477: :brod_producer.d
    ````
    
    I can t seem to figure out what the issue so far looking at the code.

**Comment by epinault** [comment]
also changing

```
compression: :snappy 
```

and adds snappyer, with recompiling also brod then seems to work

**Comment by zmstone** [comment]
Hi @epinault 
`:snappy` should be the correct atom to use.
I couldn't seem to find where in the code base `:snappyer` is advised to use, cold you point me to it so we can fix it.

**Comment by epinault** [comment]
yea I think what induced me in error are 2 things

https://github.com/kafka4beam/kafka_protocol/blob/master/src/kpro_compress.erl#L28

and also the fact that the params have to be an atom and not a string (brod did not make that clear other than come and check your README here) 

also I think the README could benefit to be more clear for snappy 

https://github.com/kafka4beam/kafka_protocol/blob/master/README.md#compression-support

it mentions snappier but only show the example for lz4 and how to pass a custom module. 

Maybe being explicit for the supported one on what to add and then how to make your own  in a separate section?

finally , reminding that now you need to add the dependency in your app (I had to add snappier) and ensure to recompile brod would also help 

thanks for the prompt reply !
