### ISSUE TITLE
oauth2

### ISSUE THREAD

**Issue by zmstone** [kafka4beam/kafka_protocol#111]
https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=75968876
https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=186877575

**Comment by indrekj** [comment]
Do you know the rough outline of what it would take to implement this?

**Comment by zmstone** [comment]
Hi @indrekj 
I am not sure when I will be able to work on this.

**Comment by zmstone** [comment]
SASL/OAUTHBEARER is now supported by: https://github.com/HCA-Healthcare/brod_oauth
