### ISSUE TITLE
Does not compile on Erlang/OTP 27

### ISSUE THREAD

**Issue by mashton** [kafka4beam/kafka_protocol#125]
### Issue
kafka_protocol fails to compile on Erlang/OTP 27 due to transitive dependency port_compiler (pc) pinned by crc32cer at 1.14.

### Reproduce

1. `> mix new .`
2. add `{:kafka_protocol, "~> 4.1"}` to deps
3. `> mix deps.get`
4. `> DIAGNOSTIC=1 mix deps.compile`
Result:
`Could not compile dependency :crc32cer`

### My analysis

kafka_protocol pins crc32cer to `0.1.8`
crc32cer `0.1.8` pins port_compiler to `1.14`
port_compiler (pc) [doesn't play nice with Erlang 27](https://github.com/blt/port_compiler/issues/82) but is fixed in 1.15

### Fix?
crc32cer `0.1.11` uses pc `1.15` [see commit here](https://github.com/zmstone/crc32cer/commit/0a0b7f606a2d2963ec4e012b385e5beb4a918fa8)

While I understand that plugins can be upgraded locally, it is also my understanding that because crc32cer pins the pc version, we'll still get the old port_compiler.

So it's my understanding that updating crc32cer to `0.1.11` will fix this.

Would be happy to try my hand at a PR. As you can see I'm an Elixir fella, so I might be a bit sluggish.

**Comment by zmstone** [comment]
Hi @mashton 
Thank you for reporting it.
> While I understand that plugins can be upgraded locally, it is also my understanding that because crc32cer pins the pc version, we'll still get the old port_compiler.

I think you are right, unless there is another dependency in your project which happens to pin on the same port compiler version.
