### ISSUE TITLE
Release new minor for alpine compatibility

### ISSUE THREAD

**Issue by bosak** [kafka4beam/kafka_protocol#44]
Hi,
I found out you already fixed crc32cer to support alpine image, and bumped dependency on master here.
Can i ask if you will release 2.1.2 and also brod 3.6.1 so it will work in alpine based images?

**Comment by zmstone** [comment]
2.1.2 released.
brod 3.6.1 is going to be released after this pr merge: https://github.com/klarna/brod/pull/279
