### ISSUE TITLE
crc32cer_nif_not_loaded

### ISSUE THREAD

**Issue by fxn** [kafka4beam/kafka_protocol#64]
Hi! I am using `kafka_protocol` through `elsa`, and can't get a trivial producer working because of this error:

```
iex(1)> Elsa.produce(:driver_telemetry_connection, "driver-telemetry-events", "value")
[debug] Elixir.Elsa.Producer Sending 1 messages to driver-telemetry-events:0
[info] client :driver_telemetry_connection connected to kafka:9092

[error] GenServer #PID<0.337.0> terminating
** (stop) {:crc32cer_nif_not_loaded, '/app/_build/dev/lib/crc32cer/priv/crc32cer'}
    :erlang.nif_error({:crc32cer_nif_not_loaded, '/app/_build/dev/lib/crc32cer/priv/crc32cer'})
    (crc32cer) src/crc32cer.erl:23: :crc32cer.nif/2
...
```

I wanted to report it to `crc32cer`, but the project does not have issues enabled, and the author has no email in his GitHub page, so asking here in case you have ever seen this before.

I am a bit lost. This is happening in a very simple Debian Stretch Docker container. Everything compiled inside just fine, and the `priv` directory of that lib is

```
# ls _build/dev/lib/crc32cer/priv
crc32cer.so  crc32cer_drv.so
```

Does it ring a bell by any chance?

**Comment by fxn** [comment]
I deleted `deps` and `_build`, reset all Docker stuff, and this error disappeared.

**Comment by StanAnsems** [comment]
I encountered the same issue, make sure you copy only the files to docker that you need.  Copy the right files or add the `deps` and `_build` folder to the .dockerignore
