### ISSUE TITLE
support kafka 2.x protocol

### ISSUE THREAD

**Issue by zmstone** [kafka4beam/kafka_protocol#70]
The latest version supported in `kafka_protocol` is 1.1

**Comment by slashmili** [comment]
@zmstone I'm using this library to connect to a Kafka instance on cloudkarafka.com which is running version 2.5.0. It works fine. However at the same time I can't use this library to use a managed Kafka server(2.5.0) on azure. It gets timeout on querying the version form the server.

So does library support 2.x protocol or not? 🤔

**Comment by zmstone** [comment]
Sorry I forgot to close this issue.

Kafka 2.4 is supported since `kakfa_protocol` 3.0. see changelog.md, and I quote:

> API support for Kafka 2.4 Non backward compatible changes in request/response struct field names.

I am not quite familiar with managed Kafka in azure.
How do you know if it's API version query which timed out? Do you have logs?
API query happens right after TLS handshakes.
Is TLS enabled ?

**Comment by zmstone** [comment]
@slashmili this is off topic.
I'm closing it here. Please create a new issue (maybe with more details like which version of kakfa_protocol is used, and what are the logs etc).
