### ISSUE TITLE
Drop Rebar dependency

### ISSUE THREAD

**Issue by DianaOlympos** [kafka4beam/kafka_protocol#79]
Hello, i open this as an issue because i suppose the dependency on the old rebar is due to internal process at Klarna.

Brod already use only rebar3 and kafka_protocol can use rebar3. Is there a reason you are still using both ?

I ask because rebar does not compile nicely on otp23 and this is causing all kind of pain.

**Comment by mikpe** [comment]
As far as I can tell, it should work with either rebar3 or the old rebar. What exactly doesn't work with rebar3? I.e., why do you think it depends on the old rebar?

**Comment by DianaOlympos** [comment]
The problem is that it tells hex that it needs rebar in the metadata, which means that hex crash the build if we do not provide it a rebar install to use. so it would need to drop rebar in the metadata in app.src

**Comment by zmstone** [comment]
Please help me to understand what 'hex crash the build' means.
Do you mean `mix` the build tool for elixir ?

**Comment by DianaOlympos** [comment]
Yes, basically what happens is that mix use the metadata to check if there is a local rebar installed. We have a local rebar3 but not a local rebar on our CI.

And as there is no rebar installed but kafka_protocol announce it needs it, it automatically try to install it, can't and fail the build

**Comment by zmstone** [comment]
Fine having it removed.
Removing it from metadata should not affect rebar builds (if anyone is still using it).

**Comment by DianaOlympos** [comment]
Can we get a release once that is done ? A point one should work ;) <3

**Comment by mikpe** [comment]
Tagged 3.0.1 and pushed to hex.
