### ISSUE TITLE
No such field: topic_metadata

### ISSUE THREAD

**Issue by otrochaval** [kafka4beam/kafka_protocol#81]
Hello,
    When using brod 3.15.0 to connect to a topic, I get the following error:

** Reason for termination == 
** {{{{no_such_field,topic_metadata},
      [{kpro_lib,find,2,
                 [{file,"kpro_lib.erl"},
                  {line,266}]}...

Is it because topic_metadata isn't supported in kafka version 1.1?

Thanks for bringing kafka to the erlang ecosystem!
Oscar.

**Comment by zmstone** [comment]
Could you send the full stacktrace?
I’d like to know which request/response encode/decode error it is

**Comment by otrochaval** [comment]
Sure:
=WARNING REPORT==== 15-Feb-2021::16:41:56 ===
brod_client [<0.2106.0>] my_client_id is terminating
reason: {{no_such_field,topic_metadata},
         [{kpro_lib,find,2,
                    [{file,"kpro_lib.erl"},
                     {line,266}]},
          {brod_client,do_get_metadata,2,
                       [{file,"brod_client.erl"},
                        {line,537}]},
          {brod_client,validate_topic_existence,3,
                       [{file,"brod_client.erl"},
                        {line,497}]},
          {brod_client,ensure_partition_workers,3,
                       [{file,"brod_client.erl"},
                        {line,820}]},
          {brod_client,handle_call,3,
                       [{file,"brod_client.erl"},
                        {line,348}]},
          {gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},
          {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},
          {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}

=ERROR REPORT==== 15-Feb-2021::16:41:56 ===
** Generic server my_client_id terminating 
** Last message in was {start_consumer,
                           <<"topic_name_here">>,
                           [{begin_offset,earliest}]}
** When Server state == {state,my_client_id,
                            [{"host_here",31010}],
                            undefined,[],<0.2109.0>,<0.2110.0>,
                            [{sasl,
                                 {scram_sha_512,<<"user_here">>,
                                     #Fun<brod_utils.11.45208694>}},
                             {ssl,true}],
                            my_client_id}
** Reason for termination == 
** {{no_such_field,topic_metadata},
    [{kpro_lib,find,2,
               [{file,"kpro_lib.erl"},
                {line,266}]},
     {brod_client,do_get_metadata,2,
                  [{file,"brod_client.erl"},
                   {line,537}]},
     {brod_client,validate_topic_existence,3,
                  [{file,"brod_client.erl"},
                   {line,497}]},
     {brod_client,ensure_partition_workers,3,
                  [{file,"brod_client.erl"},
                   {line,820}]},
     {brod_client,handle_call,3,
                  [{file,"brod_client.erl"},
                   {line,348}]},
     {gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},
     {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
** Client <0.2142.0> stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,169}]},
    {gen_server,call,3,[{file,"gen_server.erl"},{line,210}]},
    {brod_client,safe_gen_call,3,
                 [{file,"brod_client.erl"},
                  {line,839}]},
    {brod_topic_subscriber,handle_info,2,
                           [{file,"brod_topic_subscriber.erl"},
                            {line,306}]},
    {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,616}]},
    {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,686}]},
    {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]

**Comment by zmstone** [comment]
Which kafka_protocol version is used in your test?
Brod 3.15.0 should use kafka_protocol 2.3.6 (as in its rebar.config)

**Comment by otrochaval** [comment]
Yes, I had to explicitly get a newer version in rebar.config, because there was no support for lz4 compression. Now that lz4 is there, I get this new error about topic_metadata.

**Comment by otrochaval** [comment]
I'm using kafka_protocol 3.0.1 with Brod 3.15.0, otherwise lz4 compression doesn't work.

**Comment by zmstone** [comment]
`kafka_protocol` version `3.0` is not backward compatible
see summary [here](https://github.com/klarna/kafka_protocol/blob/master/changelog.md)

A quick workaround is to branch off from the last 2.x tag and add lz4 support to it.

**Comment by otrochaval** [comment]
> 
> 
> `kafka_protocol` version `3.0` is not backward compatible
> see summary [here](https://github.com/klarna/kafka_protocol/blob/master/changelog.md)
> 
> A quick workaround is to branch off from the last 2.x tag and add lz4 support to it.

Brilliant, it works!
I owe you man.
