### ISSUE TITLE
crypto:hmac is deprecated

### ISSUE THREAD

**Issue by seriyps** [kafka4beam/kafka_protocol#86]
https://github.com/klarna/kafka_protocol/blob/5569122473e2c8a00a34569ab3dc1b24d92bb674/src/kpro_scram.erl#L111

https://github.com/klarna/kafka_protocol/blob/5569122473e2c8a00a34569ab3dc1b24d92bb674/src/kpro_scram.erl#L95

https://github.com/klarna/kafka_protocol/blob/5569122473e2c8a00a34569ab3dc1b24d92bb674/src/kpro_scram.erl#L105

Builds on OTP-23 are crashing, see, eg, https://travis-ci.org/github/klarna/kafka_protocol/jobs/760231865

Can probably be fixed with some macro magic, see, eg, https://github.com/epgsql/epgsql/blob/f811a09926892dbd1359afe44a9bfa8f6907b322/src/epgsql_scram.erl#L119-L130

**Comment by zmstone** [comment]
Fixed here.
https://github.com/kafka4beam/kafka_protocol/pull/6

I can include it in #84. Or we will maybe transfer this repo to the new org depending on the “ownership” discussion

**Comment by seriyps** [comment]
Ah, ok, thanks. I was not aware of this fork.
