### ISSUE TITLE
port lz4 compression feature back to 2.x versions

### ISSUE THREAD

**Issue by zmstone** [kafka4beam/kafka_protocol#88]
lz4 was added in version 3.1
`brod` is still not upgraded yet.
it would be nice to have lz4 ported back to 2.x version.

the lz4 support can be done as a static rebar3 dependency.

**Comment by emeryotopalik** [comment]
@zmstone Do you have any idea when this will be added?

**Comment by zmstone** [comment]
brod has been upgraded to depend on latest version kafka_protocol.

however lz4 is not added as a dependency of brod, so the wrapping project which uses brod as a dependency should also provide lz4 lib.
for more details, see https://github.com/kafka4beam/kafka_protocol/blob/master/README.md#compression-support
