### ISSUE TITLE
Wrong key for delete_topics

### ISSUE THREAD

**Issue by tpitale** [kafka4beam/kafka_protocol#90]
Should this be `topic_names` instead of `topics`? https://github.com/kafka4beam/kafka_protocol/blob/master/src/kpro_req_lib.erl#L360

As per the bnf here https://github.com/kafka4beam/kafka_protocol/blob/master/priv/kafka.bnf#L3781

I'm trying to get tests working in `brod` against the released version of `kafka_protocol` 3.1.0 and I have two tests failing because:

```
{{field_missing,[{stack,[{delete_topics,0},topic_names]},
                 {input,#{timeout => 280000,topics => [<<"brod_SUITE">>]}}]},
```

**Comment by zmstone** [comment]
Hi @tpitale 
Seems to be a lack of tests in this repo.
Could you help to fix and add a test?

**Comment by tpitale** [comment]
I'll give it a shot!

**Comment by tpitale** [comment]
Can't even get `make eunit` to run. I've run `make testbed` and there are two containers running (though they're both kafka:2.4, with different names?)

This is the error I get just running tests:

```
undefined
*** test generator kpro_fetch_tests:fetch_test_/0 failed ***
**in function kpro_test_lib:with_connection/4 (/Users/tpitale/Development/OSS/kafka_protocol/test/kpro_test_lib.erl, line 131)
in call from kpro_fetch_tests:get_api_vsn_range/1 (/Users/tpitale/Development/OSS/kafka_protocol/test/kpro_fetch_tests.erl, line 247)
in call from kpro_fetch_tests:fetch_test_/0 (/Users/tpitale/Development/OSS/kafka_protocol/test/kpro_fetch_tests.erl, line 30)
in call from eunit_test:'-mf_wrapper/2-fun-0-'/2 (eunit_test.erl, line 273)
in call from eunit_test:run_testfun/1 (eunit_test.erl, line 71)
in call from eunit_data:parse/1 (eunit_data.erl, line 239)
in call from eunit_data:next/1 (eunit_data.erl, line 175)
in call from eunit_data:lookahead/1 (eunit_data.erl, line 530)
**error:{badmatch,{error,timeout}}
```

So, it looks like it times out on connecting to something.

**Comment by tpitale** [comment]
Weirdly, other tests are running and connecting to kafka. Just trying to track down what's up with this one fetch test.

**Comment by tpitale** [comment]
Found at least part of the issue:

If I get metadata of the docker instance on localhost:9092 it returns the docker ip 172.17.0.3:9092 … but I can't reach that from the host. So something in the config of docker is wrong … like the network mode?

Or maybe I should be running `make eunit` inside docker?

**Comment by tpitale** [comment]
```
scripts/run-eunit.sh kpro_fetch_tests
Erlang/OTP 23 [erts-11.1.8] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Eshell V11.1.8  (abort with ^G)
1> ======================== EUnit ========================
DiscoveredEndpoint: {<<"172.17.0.3">>,9092}
undefined
*** test generator kpro_fetch_tests:fetch_test_/0 failed ***
**in function kpro_test_lib:with_connection/4 (/Users/tpitale/Development/OSS/kafka_protocol/test/kpro_test_lib.erl, line 131)
in call from kpro_fetch_tests:get_api_vsn_range/1 (/Users/tpitale/Development/OSS/kafka_protocol/test/kpro_fetch_tests.erl, line 247)
in call from kpro_fetch_tests:fetch_test_/0 (/Users/tpitale/Development/OSS/kafka_protocol/test/kpro_fetch_tests.erl, line 30)
in call from eunit_test:'-mf_wrapper/2-fun-0-'/2 (eunit_test.erl, line 273)
in call from eunit_test:run_testfun/1 (eunit_test.erl, line 71)
in call from eunit_data:parse/1 (eunit_data.erl, line 239)
in call from eunit_data:next/1 (eunit_data.erl, line 175)
in call from eunit_data:lookahead/1 (eunit_data.erl, line 530)
**error:{badmatch,{error,timeout}}


=======================================================
  Failed: 0.  Skipped: 0.  Passed: 0.
One or more tests were cancelled.
```

**Comment by zmstone** [comment]
Hi. are you running the tests in macOS? Docker in mac has such network issues. 

For brod we use this to make it work. https://github.com/kafka4beam/brod/blob/582f95cf01a1d72334078f0a31b6e6fd22f2051d/scripts/docker-compose.yml#L5

Maybe we can copy the docker-compose file here

**Comment by tpitale** [comment]
Yep, definitely a Docker + Mac thing. I'm looking at bringing docker-compose into this project to replace setup-testbed. 🤞🏼

**Comment by tpitale** [comment]
Got it (mostly) running with compose. Certainly more than before.

Now I _can't_ get it to error on `delete_topics` 😂

**Comment by zmstone** [comment]
@tpitale are you sure you have master branch checked out? or recompiled the beams ?

I tried it like this:
```
$ erl -pa _build/default/lib/*/ebin
Eshell V10.7.2  (abort with ^G)
1> kpro_req_lib:delete_topics(0, [<<"a">>], #{}).
** exception error: {field_missing,[{stack,[{delete_topics,0},topic_names]},
                                    {input,#{timeout => 0,topics => [<<"a">>]}}]}
     in function  kpro_req_lib:enc_struct/3 (kpro_req_lib.erl, line 459)
     in call from kpro_req_lib:encode_struct/3 (kpro_req_lib.erl, line 439)
     in call from kpro_req_lib:make/3 (kpro_req_lib.erl, line 393)
```

**Comment by tpitale** [comment]
Oh yeah. I can get the error when I try to use it. But doing the same thing in the tests in `kpro_topic_mngr_tests` doesn't error here: https://github.com/kafka4beam/kafka_protocol/blob/master/test/kpro_topic_mngr_tests.erl#L161 like I would expect.

**Comment by tpitale** [comment]
```
▶ make clean compile
===> Verifying dependencies...
===> Cleaning out kafka_protocol...
===> Verifying dependencies...
===> Analyzing applications...
===> Compiling kafka_protocol
Development/OSS/kafka_protocol  docker-compose-for-test ✔                                                                                                                                                                                                             16h39m  
▶ scripts/run-eunit.sh kpro_topic_mngr_tests              
Erlang/OTP 23 [erts-11.1.8] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Eshell V11.1.8  (abort with ^G)
1> ======================== EUnit ========================
module 'kpro_topic_mngr_tests'
  kpro_topic_mngr_tests: create_topic_partition_test_...[0.260 s] ok
  kpro_topic_mngr_tests: describe_configs_test...[0.063 s] ok
  kpro_topic_mngr_tests: alter_configs_test...[0.075 s] ok
  kpro_topic_mngr_tests: delete_topics_test...[0.003 s] ok
  [done in 0.425 s]
=======================================================
  All 4 tests passed.
```

**Comment by tpitale** [comment]
If I change the keys for `delete_topics` to `topic_names` and `timeout_ms` the above `erl` example works properly. So there is definitely something there.

**Comment by zmstone** [comment]
embarrassing mistake from 3 years ago, it's a eunit generator, the test function name should be `delete_topics_test_`
(ends with an underscore).
ref: http://erlang.org/doc/apps/eunit/chapter.html#Writing_test_generating_functions

**Comment by tpitale** [comment]
Hooray! That change made it error in the tests. Now I can fix it 😄

**Comment by tpitale** [comment]
@zmstone Is the same true for `describe_configs_test` and `alter_configs_test` (they should end in `_`)?

**Comment by tpitale** [comment]
Also … `create_topic_partition_test_` uses `make_random_topic_name()` to create the topics. But the other functions look for topics with `get_test_topics`, which appears to look for the topic to be prefixed with the `?MODULE`.

**Comment by zmstone** [comment]
Hi @tpitale `describe_configs_test` and `alter_configs_test` are test functions, not generators.
test generator returns either a function, a tuple like `{timeout, Time, fun()}` or a list of such.

We can use random topics for all test cases,
only we need make sure a topic is created before testing `get` and `delete`

**Comment by tpitale** [comment]
@zmstone Here's the start of my PR: https://github.com/kafka4beam/kafka_protocol/pull/91

I've got it running locally with docker compose (`make test-env enuit`) except for semi-random failures in `kpro_group_tests` module 🤔

**Comment by zmstone** [comment]
yes, the group test is a bit flaky
